vo_ipui_admin:
    resource: "@VoIPUIAdminBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ippbxami:
    resource: "@VoIPPBXAMIBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ippbx_bill:
    resource: "@VoIPPBXBillBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ip_company_voicemail:
    resource: "@VoIPCompanyVoicemailBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ippbxcdr:
    resource: "@VoIPPBXCDRBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ip_company_subscriptions:
    resource: "@VoIPCompanySubscriptionsBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ipui_basic:
    resource: "@VoIPUIBasicBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ip_company_structure:
    resource: "@VoIPCompanyStructureBundle/Controller/"
    type:     annotation
    prefix:   /

management_session_user:
    resource: "@ManagementSessionUserBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ip_dynamic_ip_daemon:
    resource: "@VoIPDynamicIPDaemonBundle/Controller/"
    type:     annotation
    prefix:   /

vo_ippbx_real_time:
    resource: "@VoIPPBXRealTimeBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /parameters

